services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # mount whole backend dir
      - models_data:/app/models # separate volume for models
    depends_on:
      - frontend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
volumes:
  models_data:
