services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - models_data:/app/models
    depends_on:
      - frontend
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usedcars-backend.rule=Host(`api-used-cars-price.gkibria121.com`)"
      - "traefik.http.routers.usedcars-backend.entrypoints=web"
      - "traefik.http.services.usedcars-backend.loadbalancer.server.port=8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usedcars-frontend.rule=Host(`used-cars-price.gkibria121.com`)"
      - "traefik.http.routers.usedcars-frontend.entrypoints=web"
      - "traefik.http.services.usedcars-frontend.loadbalancer.server.port=3000"

volumes:
  models_data:

networks:
  traefik-network:
    external: true
